#!/bin/bash
iptables -F
ip6tables=/system/bin/ip6tables
iptables=/system/bin/iptables
iptables -I OUTPUT -p all -m string --string  --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 01a---zl-5uiv6dsq.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 04-wtm-akamai.cdn.gaijin.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 04host.qq.com.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 05-wtm-akamai.cdn.gaijin.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 09n---f9-lykphsyw.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 0op---as-au18mpoa.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 0pa---bx-pyufgiog.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 0pn---aq-a1nsssia.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 0ys---ss-hnomfjgg.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 10046.link --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 12345.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 12456.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 127vod-adaptive.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 12t---ca-u6xqbouq.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 13456.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 13vod-adaptive.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 145575.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 146096.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 147238.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 147857.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 149759.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 1515mu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 156e03f65b76082e.42s.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 19qq.com.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 207.mcraft.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 20playrix.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 234658.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 2playrix.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 498755.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 5120.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 52wpojie.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 580944.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 5zy.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 70424.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 778878.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 80842.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 80994.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 85464.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 86494.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 8cc7.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 91ld.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 91vps6.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 91xy.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 92cs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 9a6---w7-b8byctyg.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 9hgame.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a1574.b.akamai.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a3.v.akamai.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a449.d.akamai.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a516.g.akamai.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a798.ms.akamai.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string abpananda.abplive.in --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string abtest.mistat.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string account.wandoujia.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string acroipm.adobe.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string act.e.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ad.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string adashx.ut.cainiao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string adisneyparks.disney.go.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string admin.mixin.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string adv.aiclk.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aesop.iep.edu.gr --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ahsyxx.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ai.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aischedule.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ak.dynamic.t0.tiles.virtualearth.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string akmbattle2.infinity8ball.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ali.reaist.cloudns.biz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alibaba.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alidns.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aliyun.bbs-img.zsdown.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alt7.mtalk.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alt8.mtalk.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string amzdigital-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string analytics.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string antennalem-lh.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aod.itunes.apple.com.edgesuite.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apd-pcdnvodstat.teg.tencent-cloud.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apd-pcdnwxstat.teg.tencent-cloud.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apd2.payba.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-aicall.aiasst.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-third.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.aliyundrive.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.biubiu001.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.huangye.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.jietuhb.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.mcc.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.misim.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.music.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.qquanquan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.speaker.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api7.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apm-rum.inf.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app10006.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app1013.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app110746.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app111340.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app113991.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app114163.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app117477.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app121419.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app127741.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app32362.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app4290.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app48201.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app81011.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app82759.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app86928.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apps.teambition.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string auth.aliyundrive.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string auto.news18a.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string autopatchhk.yuanshen.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ava-dl.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string b.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string baobiao.iyunzhi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bbs-avatar.mt2.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bbs.9game.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bbs.binmt.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bgmi.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string blzmedia-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bnetaccount.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string book.uc.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bookmark.api.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bot.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string box.pandora.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cache.redflagblog.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cache.redflagblog.info --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cache.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cache.redflagblog.org --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cache.redflagblog.xyz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cadenaser.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string callback.eco.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string calm4.keruyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string card.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cartoonnetwork.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cbcnewshd-f.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cc.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cc2.sys.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ccc.sys.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn.dgshengyao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn.fastclick.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn2-prod-cfn.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn3-aka.makeshop.co.kr --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string chapangzhan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string chatous.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string clientconfig.akamai.steamstatic.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloud.gsdk.proximabeta.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloudinter-linkgatewayonline.sto.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string club.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string collection.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string connect.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string connect.duokan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string connect.rom.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string connectionflood.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string content.mcc.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string content.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string content.sqreader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string coupons.thedailybeast.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cv.shopee.co.id --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string d3cq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string d7a.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string data.huizhijiaxun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string database.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string db.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dbs5.gytlxx.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dcpi.disney.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ddos.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string development.krmobile.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dhfsf.heytapimage.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string diagnosis.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string diandong.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dl.listdl.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dl.mt2.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns1.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns2.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns2tcp.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns2tcpc.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns3.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns3.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns8.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns8.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnsflood.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnsproxy.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnsproxyserver.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnsproxyservice.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnsqueryflood.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnstunnel.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string down.hangame.co.jp --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.xboxlive.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string duba2.3ge.club --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dusbdis.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dy5533m.wbet68.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ele.to --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string epmgr.bsp.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string erp.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string esp.mioffice.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string espaceclientcanal.canal-plus.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string euspeed.igamecj.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string evan66.fun --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string event.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string eventlog.1sapp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string extranet-alllines-pub-c3-c4.alb.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fb-l-c-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fcapi.0d3ed00.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fgtvlive.fgtv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fileserver1.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string flrcw.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fm.duokanbox.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fq.mk --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string friends.rnps.dl.playstation.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fx-instruments.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string g2.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gamedownloads-rockstargames-com.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gameloft.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ganode.org --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gbzc.eapps.dingtalkcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gcm-xmpp.googleapis.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gcm.googleapis.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gf.mt2.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gitlab.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gmobile.da961b9.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string goldmine.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gomatch.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gomeet.today --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string grayconfig.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string grvmqm.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gta.teambition.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string guocangart.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string gw.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string h5.ai.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string h5.battlegroundsmobileindia.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string h5.jn5mrhvd.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string h5hosting-drcn.dbankcdn.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string haoyou666.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string haoyou888.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hk.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hkspeed.igamecj.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hls3a-akm.douyucdn.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string host0.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string host101.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string host3.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string host7.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hostmaster.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hotasp.v.cntv.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string http.microsoftcs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string huweibc.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hy.9game.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hybrid.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hybrid.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string i.99166.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string i2.help.outlook.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ics-speech.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ieohd-vh.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string if.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string iforum-de.c.hihonor.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string images.blur.io --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string img-prod-cms-rt-microsoft-com.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string img.eqiyingxiao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string img.jingyu77.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string info.sec.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ip.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string itsm.rajax-inc.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ixs.sm.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string jf.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string jinsema.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string jjbao8.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string jkbaby.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string joinus.rajax-inc.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string joycrafter.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string k-toggle.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string k.gjacky.com.cdn.ettdnsv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string kancq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string kr.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string kxdhxx.30edu.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string live.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string livecloud.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string load.xiaoning168.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string logigames.bet9ja.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ludia.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m-v16.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.51cmm.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.962.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.bibi2022.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.biubiu001.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.gbuvip.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.shuozhiwu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.shuqiread.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mail1.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string manage.igmobile.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string map.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mapi.sandbox-bjj.co.id --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string matrix653.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string message.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string miaowoo.club --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string micar-lottery.browser.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mimc.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mini.bbcallworld.top --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mip.btcha.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mip.fanvz.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mkgb.gcdn.netmarble.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mlog.search.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mobile-gtalk.l.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mon-va.byteoversea.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string movie.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string movie.phinf.naver.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mt2.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mtalk-staging.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mtalk4.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string music.search.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string my-zfx.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string my.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mysql.block.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string myurl1.gytlxx.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string na.pandora.qq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string namtso.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string napubgm.broker.amsoveasea.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string nawzryhwatm.broker.amsoveasea.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string netroam.mihome.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string new-asx.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string newmars-client-package.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string news.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string newwatch.slingbox.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string next.itellyou.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string nhkwlive-rj.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string noticeboard.netmarble.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ns1.block.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ns1.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string nsa.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ntd02.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string nus.cdn.wup.shop.nintendo.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string o2o.api.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string oc.yuekeyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ocean.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string old-mobile.bet9ja.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string on.shuqiread.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string open-schedule.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string open.teambition.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string openssh.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string opensshproxy.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string opensshserver.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string opensshservice.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string opensshtunnel.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string oracle.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string order.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string p10445-friend.ejoy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string p10445-gangplank.ejoy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string p10445-launcher.ejoy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string p10445-user-info.ejoy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string p16-sign-useast2a.tiktokcdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string p3ins.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string package.work.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pan.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pansitech.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string partner.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string payment.api.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pccw-live-cdn-01.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pic-bstarstatic.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string playdemic.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string playmc2.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pop3.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string post.net.playstation.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string potatso.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string powerbi-bj.dp.pt.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string prd-vod06.akamai.tvbanywhere.com.sg --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string preview.exapi.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string preview.pay.notify.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string prfzquobemaspprl-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string product.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pub.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string public.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string public.myoffer.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string public1.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string public2.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string public9.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string publicl.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string puffs.fun --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pupgm.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string qintop.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string qookagames.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string qq.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string rcv.aiclk.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string rdns.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string replay151.valve.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string replay223.valve.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string replay231.valve.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string res.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string resource.4852a37.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string rthktv31-live.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string s.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string s.mi.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string s1.s.360xkw.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string s16.kwai.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sa.mcc.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string safe.mt2.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string saozi.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sc.mvlveq25.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string scholar.harvard.edu --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string screentime.comm.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sec.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string secure.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string secureshell.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string secureshellproxy.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string secureshellserver.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string secureshellservice.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string secureshelltunnel.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string seller.tokopedia.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sensorsdata.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sensorsdata.read.duokan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sentry.d.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sf16-ttcdn-tos.pstatp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sgzbbs.lingxigames.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shextshort.weixin.qq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shop.bet9ja.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shop.binmt.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shop.mt2.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string short.weixin.qq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shuidi.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shundeyanyi.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sieffi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string site.e.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string smartinfo.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sms.pt.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sos.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string spay2.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string spend1.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string spend1sq.uc.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sports-tracker.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ssh.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ssh.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sshproxy.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sshserver.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sshserviceserver.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sshtunnel.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ssp.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string stars.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string static.i.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string stats-fm.music.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string stats.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string support.teambition.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string syx-edu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sz-maga.biubiu001.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string t.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string t2.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string t6pubgmobile.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ta-receiver-cn.g.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string taobao.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string taomee.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string taozhuang.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tbs.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tburl.in --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string teambitionapis.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tencent.block.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tencentgames.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string test.log.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string test.zeus.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string testhub.teambition.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string thoughts.teambition.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tmall.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tophatch.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string trace-api.aiclk.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string trail.e.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string translator.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tun.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tv.weixin.pandora.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string twoo-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string uaespeed.igamecj.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ubistatic11-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ubistatic3-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string unlock.update.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string update0.aiclk.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string update0.qquanquan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string userprofile.shuqireader.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string v.jstv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string v16-cc.capcut.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string v16.muscdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vas-alisg16.byteoversea.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vdo-live-cache-akamai.cdn.tvb.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vip.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vip3.avip4.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vod133-ttvnw.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wanapi.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wap.demowx.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wechat.chengquan.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wgetapi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string whatismyip.akamai.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string while.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string whippet.bsp.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string whole.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wm958.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wms5-kortv.akamaized.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wpk.ucweb.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wr.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wsapp.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.005672.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.09ww.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.10100.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.105444.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.1556yabo.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.2278.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.2cai11.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.2d3d5d.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.373267.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.3f3a9.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.42s.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.44c11.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.498755.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.5178win.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.521.xyz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.52cq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.5577.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.576tv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.5cq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.5zy.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.62311111.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.7558xqpp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.80cqsf.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.828820.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.860bafa.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.86661.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.92cs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.93lh.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.97xonline.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.9999czj.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.999skins.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.9c7993.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.abs-cbn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ali-jk.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.alihealth.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.aliyundrive.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.app.tennistv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.autowini.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.baa4ba.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.babble.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.badlanders.game --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.belezanaweb.com.br --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.bellelily.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.bellelily.com.edgesuite.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.biubiu001.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.bj-alihealth.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.blueman.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.businesstoday.in --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.cmg.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.cp1996.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.cqcb.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.d3cq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.dgt.es --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.disneybaby.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.edrawsoft.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.eggyparty.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.eluniversalpuebla.com.mx --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.eset.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.evoicl.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.fcw4.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.fpie2.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.fpie5.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.fpie7.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.fpie8.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.gbuvip.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.gift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.gnomic.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.15680166162.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.15680166165.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.httpdnsapi.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.q3664356365.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.qq1977832490.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.qqqun878763748dnsflood.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.google.com.hk.qun878763748dnsflood.redflagblog.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.granitifiandre.biz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.h6y55.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.hankooktire.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.hindustantimes.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.hottubtimemachine.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.huobi.com.sn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ina.de --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.iom.int --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.j5h6p.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.jpstgame.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.jstv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ka-cn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.kaletou.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.kangkanglu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.kaolamedia.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.kiss104fm.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.kooapp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ku234.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.lanacion.com.ar --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.latticesemi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.lixianghualai.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.macaotourism.gov.mo --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.macromedia.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.mexc.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.missionevo.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.moguding.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.mumuglobal.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.mypa7.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ng5.app --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ovzljupx.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.planetfashion.in --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.pokerstars.uk --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.primarius-tech.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.pubgmobile.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.pubgmobile.com.cdn.ettdnsv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.pubgmobile.com.edgesuite.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.qm333.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.qnrcy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.shuiguopai88.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.similarweb.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.steamhm.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.taohuaex.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.tburl.in --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.teambition.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.tf1.fr --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.theboneonline.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.tiktok.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.tyqoon.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.viveusa.mx --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.vv881.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.watchhungerstop.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.wbzol.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.wftv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.woxiu2.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.wpxi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.xhyapp1.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.xiaoji.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ydss.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.zhuozhengsoft.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.zz91.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www1.helpshift.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wwwhm.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wx.17u.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wxv---rn-dhdo4lfw.alidns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wzm-and-loginservice.prod.demonware.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xhyios2.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xiaoshuo.uc.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xigncode.mangot5.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xkyy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xlog.byteoversea.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xs.sm.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xtb.damai.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string yc.shuqi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ygn.4b9648903.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string yryirjrhqffsxwpg-a.akamaihd.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zeus.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zhaoshang.alihealth.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zhiyinnav.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zxkjlc.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zy.wweenn.cn --algo bm -j DROP
iptables -I INPUT -s 101.227.131.167 -j DROP
iptables -I INPUT -s 101.227.131.222 -j DROP
iptables -I INPUT -s 110.42.1.55 -j DROP
iptables -I INPUT -s 118.26.253.153 -j DROP
iptables -I INPUT -s 118.26.253.179 -j DROP
iptables -I INPUT -s 119.28.229.113 -j DROP
iptables -I INPUT -s 120.78.74.132 -j DROP
iptables -I INPUT -s 127.8.0.1 -j DROP
iptables -I INPUT -s 129.226.2.165 -j DROP
iptables -I INPUT -s 14.18.202.194 -j DROP
iptables -I INPUT -s 162.62.80.220 -j DROP
iptables -I INPUT -s 162.62.81.167 -j DROP
iptables -I INPUT -s 162.62.81.208 -j DROP
iptables -I INPUT -s 162.62.81.87 -j DROP
iptables -I INPUT -s 162.62.81.90 -j DROP
iptables -I INPUT -s 166.101.188.151 -j DROP
iptables -I INPUT -s 173.194.174.188 -j DROP
iptables -I INPUT -s 175.6.84.111 -j DROP
iptables -I INPUT -s 180.111.196.239 -j DROP
iptables -I INPUT -s 184.26.127.17 -j DROP
iptables -I INPUT -s 211.159.174.153 -j DROP
iptables -I INPUT -s 220.181.52.24 -j DROP
iptables -I INPUT -s 222.189.172.22 -j DROP
iptables -I INPUT -s 223.5.5.5 -j DROP
iptables -I INPUT -s 3.229.41.0 -j DROP
iptables -I INPUT -s 3.232.59.33 -j DROP
iptables -I INPUT -s 47.92.40.45 -j DROP
iptables -I INPUT -s 47.92.40.46 -j DROP
iptables -I INPUT -s 58.220.52.204 -j DROP
iptables -I INPUT -s 59.82.133.168 -j DROP
iptables -I INPUT -s 60.191.87.84 -j DROP
iptables -I INPUT -s 61.213.168.48 -j DROP
iptables -I OUTPUT -d 101.227.131.167 -j DROP
iptables -I OUTPUT -d 101.227.131.222 -j DROP
iptables -I OUTPUT -d 110.42.1.55 -j DROP
iptables -I OUTPUT -d 118.26.253.153 -j DROP
iptables -I OUTPUT -d 118.26.253.179 -j DROP
iptables -I OUTPUT -d 119.28.229.113 -j DROP
iptables -I OUTPUT -d 120.78.74.132 -j DROP
iptables -I OUTPUT -d 127.8.0.1 -j DROP
iptables -I OUTPUT -d 129.226.2.165 -j DROP
iptables -I OUTPUT -d 14.18.202.194 -j DROP
iptables -I OUTPUT -d 162.62.80.220 -j DROP
iptables -I OUTPUT -d 162.62.81.167 -j DROP
iptables -I OUTPUT -d 162.62.81.208 -j DROP
iptables -I OUTPUT -d 162.62.81.87 -j DROP
iptables -I OUTPUT -d 162.62.81.90 -j DROP
iptables -I OUTPUT -d 166.101.188.151 -j DROP
iptables -I OUTPUT -d 173.194.174.188 -j DROP
iptables -I OUTPUT -d 175.6.84.111 -j DROP
iptables -I OUTPUT -d 180.111.196.239 -j DROP
iptables -I OUTPUT -d 184.26.127.17 -j DROP
iptables -I OUTPUT -d 211.159.174.153 -j DROP
iptables -I OUTPUT -d 220.181.52.24 -j DROP
iptables -I OUTPUT -d 222.189.172.22 -j DROP
iptables -I OUTPUT -d 223.5.5.5 -j DROP
iptables -I OUTPUT -d 3.229.41.0 -j DROP
iptables -I OUTPUT -d 3.232.59.33 -j DROP
iptables -I OUTPUT -d 47.92.40.45 -j DROP
iptables -I OUTPUT -d 47.92.40.46 -j DROP
iptables -I OUTPUT -d 58.220.52.204 -j DROP
iptables -I OUTPUT -d 59.82.133.168 -j DROP
iptables -I OUTPUT -d 60.191.87.84 -j DROP
iptables -I OUTPUT -d 61.213.168.48 -j DROP
