#!/bin/bash
iptables -F
ip6tables=/system/bin/ip6tables
iptables=/system/bin/iptables
iptables -I OUTPUT -p all -m string --string  --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 0lqbbxnw.oml5rbdnslqmsebd.jtp3015.top --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 10046.link --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 117.wefun.vip --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 15.au.download.windowsupdate.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 1753690062.zapto.org --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 21qp.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 2ww.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 36xiu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 4694.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 4nk.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 586.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 679km.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 91m.top --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string 99jpk.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a.liyi666.eu.org --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string a0.app.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string abc.tlsy.vip --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string abtest.mistat.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ac.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string account-cn.alibabacloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string account.www.net.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string act.e.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ad.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string adam.console.alibabacloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string adash-emas.cn-hangzhou.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string admin.mixin.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ai.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ai.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aischedule.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string algoprolog.saiya100.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aliyun-adns.aliyun.com.gds.alibabadns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string aliyun.gein.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alt1-mtalk.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alt3-mtalk.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alt4-mtalk.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string alt8-mtalk.google.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-aicall.aiasst.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-ecn-kingdata.ksyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-kingdata.ksyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-third.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api-tj.kingdata.ksyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.cp12.ott.cibntv.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.installer.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.kingdata.ksyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.m.miaostreet.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.m.mshare.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.m.uczzd.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.mcc.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.misim.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.music.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.speaker.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string api.wap.guoguo-app.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apk.360buyimg.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apm-rum.inf.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apoll.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app.wgvevat.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string app.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string appcss.hicloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string appdl3.dbankcdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string appdlssl.hicloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string appimg.dbankcdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string apps.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string archive2.kylinos.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string assets1.xboxlive.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string auth.dmzu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string autopatch.sdxlmobile.173.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string autopatchcn.bhsr.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string autopatchcn.yuanshen.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string av.jdav01.xyz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string avavav.xnfxxx.xyz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string b.datangyouxic.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string b.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string b1.market.mi-img.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string b16le6kf.sched.dma.tdnsdl1.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string b6.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ba.gein.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string baike112.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string batit.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bbs.dmzu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string beacon-api.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string beian.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string beian.gein.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string best.sched.dma.tdnsdl1.cn.cdl.cdn.chinaidcnet.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bjmap-tiles-uat.kye-erp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string boce.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string box.pandora.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bsycdn.kkyou.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string bw.rvrv8818.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string callback.eco.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string card.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cc.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cc2.sys.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ccc.sys.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn-mjj-v1.npcyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn-professional-packages.chinauos.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn-professional-security.chinauos.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn-tx.7cwan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn.cnbj0.fds.api.mi-img.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn.exp.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdn.experiment.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cdndldljj.51aiwan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string chapangzhan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string chongqiyixia.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string chuangke.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cl.tjjh.hehetap.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string clienttest-g1h5.guangyv.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloudap.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloudgame-channel.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloudgame-channel2.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloudgame-emas-api.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cloudgame-ops-channel.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cn.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cn.app.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string codelife.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string connect.duokan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string connect.rom.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string content.mcc.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cos.lejunwl.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cos.yggamge.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cs.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cschat-ccs.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ctldl.windowsupdate.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string cuikai.top --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string d1-reco.a.kwimgs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string d1.a.kwimgs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dc.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dcdn.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dev.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string develop.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string developer.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dfsj-music.dbankcdn.com.cdn.dnsv1.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string diagnosis.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string digital.d88pp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dl.pddpic.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dl.yangshipin.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dlied4.myapp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dmp.www.net.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dnf404.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns.weixin.qq.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dns.www.net.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string domain.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string down.qianxunkeji.vip --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string down.wss.show --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.361757.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.cqxqlsz.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.hexun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.jiusiyu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.niuboli.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.res.chuxinhd.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download.yujua.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string download2.tanwan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dts.alibabacloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string dysms.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ednn2l3o.sched.dma.tdnsdl1.cn.cdl.cdn.sy.qy3.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string efc.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string emas.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string epmgr.bsp.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string esp.mioffice.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string exmail.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string extranet-alllines-pub-c3-c4.alb.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string feedback-api.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fga1.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string file.cdn.cqttech.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string flying1008.top --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string fm.duokanbox.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string game.4399iw2.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string game.vipdks.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string grayconfig.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string greencode.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string guid.payba.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string guid.tpns.sh.tencent.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string guru55.xyz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string h5.ai.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string he8nvbq7.dayugslb.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string help-ccs.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hiboard.dbankcdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hjmall.dmzu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hjsc.dmzu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hjyj.125yy02.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string home-intl.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string home.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string homenew.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hotfix-api.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string huojian.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hybrid.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string hybrid.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ics-speech.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string img.kuaiwenyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string iot.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string iotx-cellnet-tns-vpc-sh.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string iotx-vision-p2p-signal-vpc-sh.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ip.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string it.zte.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string jg.awaliwa.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string jt.zhifujiwen.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string log.tpns.sh.tencent.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string logcloud.ksyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string logo.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.app.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.app.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.golue.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.track.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m.yunos.wasu.tv --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string m1.static.yximgs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mail.guff.in --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string market.tianchi.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mcleak.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mdns.mcast.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mias.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string micar-lottery.browser.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mimc.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string miniapp.gtimg.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mlog.search.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mp3.bookmall.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mpaas.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mpush-api.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mqtt.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string music.search.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string mvmusic1.meitudata.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string my.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string netroam.mihome.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string new-developer.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string nls-wave.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string o2o.api.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string office.chovaa.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string offlinev2.gtimg.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pan.y1x1.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pan.zai1.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string panda.www.net.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string partner.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pay.atongkj.top --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ping.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string portal-cn-shanghai.alibabacloudsso.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string powerbi-bj.dp.pt.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pp.ting55.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string preview.exapi.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string preview.pay.notify.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string product.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string proxy-tc.58pic.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pub.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pwx.woozooo.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string pypi.doubanio.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string q-arts.123u.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string r.app.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string rdsnext.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string s.mi.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sa.mcc.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sany.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string scholar.scqylaw.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string scxs.pysmei.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sdk-api-uat.hbhhslzp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sensorsdata.10046.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sensorsdata.read.duokan.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sentry.d.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string setting-emas.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string share5.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shextshort.weixin.qq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shop07i13195.market.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string short.weixin.qq.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string shuidi.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string site.e.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string smartinfo.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sms.pt.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string sos.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ssp.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string stat.tpns.sh.tencent.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string static.i.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string stats-fm.music.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string store.sany.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string swas.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string t.track.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ta-receiver-cn.g.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string test.log.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string test.zeus.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string testdx.baka9.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ti.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tjscdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tlog-emas.aliyuncs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tlu.dl.delivery.mp.microsoft.com.cdn.dnsv1.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tm.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tm.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tracedm.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string trail.e.mi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string translator.ai.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tv.weixin.pandora.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tvka.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tvmsr.gtimg.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string tyjr-common-cn-shanghai.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string unlock.update.miui.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string unsz.api.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string unzbmix25g.api.m.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string update.ss.igreatdream.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string updatecdn.meeting.qq.com.cdn.dnsv1.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string upoll.umengcloud.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string upos-sz-staticcos.bilivideo.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vatplat.gtimg.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string vision.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wap.taobao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string weatherapi.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string whois.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wsapp.chat.xiaomi.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wtradv.market.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wu-bg-shim.trafficmanager.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www-jp-de-intl-adns.aliyun.com.gds.alibabadns.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.1204.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.139sp.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.21qp.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.28283.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.2sf.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.3body.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.554321.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.5681.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.63388.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.66skins.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.7czs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.7e.hk --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.8x6x.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.91yu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.92wansy.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ahsjms.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.alimei.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.ar312.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.beigo.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.dmzu.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.download.windowsupdate.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.gein.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.hscc.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.jb8bk.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.jhopi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.loushang.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.lulu123.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.maomi.love --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.mtbbs.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.pi7.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.qingyunl.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.qk.com.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.shbge.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.siluxiangtian.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.sudiao.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.taikongsha.cc --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.taojin188.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.thsj.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.tianchi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.uipps.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.xprinter.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.yxhrhg.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.yysss.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.zjyddj.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.zmthome.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string www.zxy73.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string wzjh-xcx-res.vxingvyou.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xbzl-cdn.dyhyyx.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xcimg.szwego.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xlauncherv2qq.xoyocdn.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xm75.cn --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xvideos.xxsaobi.xyz --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xvideos.zhaofeizi.co --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string xvideos.zhaosaozi.co --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string yinxydlf.leiting.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string yq.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string yundun.console.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string yunqi.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zeus.ad.xiaomi.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zgps.net --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string zijian.aliyun.com --algo bm -j DROP
iptables -I OUTPUT -p all -m string --string ztby-res.vxinyou.com --algo bm -j DROP
iptables -I INPUT -s  -j DROP
iptables -I INPUT -s 101.226.150.121 -j DROP
iptables -I INPUT -s 106.11.249.99 -j DROP
iptables -I INPUT -s 106.11.53.98 -j DROP
iptables -I INPUT -s 110.43.121.63 -j DROP
iptables -I INPUT -s 117.89.176.67 -j DROP
iptables -I INPUT -s 117.89.177.97 -j DROP
iptables -I INPUT -s 118.26.252.225 -j DROP
iptables -I INPUT -s 118.26.253.72 -j DROP
iptables -I INPUT -s 121.4.8.102 -j DROP
iptables -I INPUT -s 122.246.26.125 -j DROP
iptables -I INPUT -s 122.246.26.92 -j DROP
iptables -I INPUT -s 123.151.48.208 -j DROP
iptables -I INPUT -s 140.205.160.4 -j DROP
iptables -I INPUT -s 140.205.162.6 -j DROP
iptables -I INPUT -s 182.254.116.117 -j DROP
iptables -I INPUT -s 203.107.1.66 -j DROP
iptables -I INPUT -s 220.181.106.14 -j DROP
iptables -I INPUT -s 220.181.106.32 -j DROP
iptables -I INPUT -s 220.181.52.136 -j DROP
iptables -I INPUT -s 220.181.52.253 -j DROP
iptables -I INPUT -s 221.233.216.61 -j DROP
iptables -I INPUT -s 224.0.0.251 -j DROP
iptables -I INPUT -s 42.81.194.63 -j DROP
iptables -I INPUT -s 47.116.84.196 -j DROP
iptables -I OUTPUT -d  -j DROP
iptables -I OUTPUT -d 101.226.150.121 -j DROP
iptables -I OUTPUT -d 106.11.249.99 -j DROP
iptables -I OUTPUT -d 106.11.53.98 -j DROP
iptables -I OUTPUT -d 110.43.121.63 -j DROP
iptables -I OUTPUT -d 117.89.176.67 -j DROP
iptables -I OUTPUT -d 117.89.177.97 -j DROP
iptables -I OUTPUT -d 118.26.252.225 -j DROP
iptables -I OUTPUT -d 118.26.253.72 -j DROP
iptables -I OUTPUT -d 121.4.8.102 -j DROP
iptables -I OUTPUT -d 122.246.26.125 -j DROP
iptables -I OUTPUT -d 122.246.26.92 -j DROP
iptables -I OUTPUT -d 123.151.48.208 -j DROP
iptables -I OUTPUT -d 140.205.160.4 -j DROP
iptables -I OUTPUT -d 140.205.162.6 -j DROP
iptables -I OUTPUT -d 182.254.116.117 -j DROP
iptables -I OUTPUT -d 203.107.1.66 -j DROP
iptables -I OUTPUT -d 220.181.106.14 -j DROP
iptables -I OUTPUT -d 220.181.106.32 -j DROP
iptables -I OUTPUT -d 220.181.52.136 -j DROP
iptables -I OUTPUT -d 220.181.52.253 -j DROP
iptables -I OUTPUT -d 221.233.216.61 -j DROP
iptables -I OUTPUT -d 224.0.0.251 -j DROP
iptables -I OUTPUT -d 42.81.194.63 -j DROP
iptables -I OUTPUT -d 47.116.84.196 -j DROP
